default_platform(:ios)

platform :ios do
  lane :beta do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"]
    )

    build_app(
      scheme: "PhotoSweep",
      export_method: "app-store"
    )

    upload_to_testflight
  end
end
